### ISSUE TITLE
Fuel usage blinking on dedi

### ISSUE THREAD

**Issue by Quintto** [Mogli12/GearboxAddon#107] opened 2017-03-21 12:01 UTC
When I use the gearbox mod on a dedicated server, the fuel usage value keeps changing between 0 and the current value.

**Comment by Mogli12** [comment] 2017-03-22 20:15
Hi, can you please check if the problem is fixed with version 2.0.4.1? Thanks!

**Comment by Echelon2k** [comment] 2017-03-23 15:29
Problem is still there in 2.0.4.1 :(

**Comment by Mogli12** [comment] 2017-03-27 12:43
Hi, can you please check if the problem is fixed with version 2.0.4.2? Thanks!

I think that the resolution of the fuel level is too low for the fuel usage calculation. So I tried to smooth it.

**Comment by Mogli12** [comment] 2017-03-30 11:59
Any news?

**Comment by Quintto** [comment] 2017-03-30 15:59
much better now, thanks!

**Closed** 2017-05-20 11:01 UTC
Labels: enhancement
