### ISSUE TITLE
Error 3 in MP

### ISSUE THREAD

**Issue by KITT3000** [Mogli12/GearboxAddon#150] opened 2017-06-19 11:26 UTC
We have GB v2.1.2.1 and in MP we have in LOG this error:
`Error 3: E:/Gry/CDP Games/modyFS17/MP_UserB4D/FS17_GearboxAddon/gearboxMogli.lua:3089: attempt to compare nil with number`

**Comment by Mogli12** [comment] 2017-06-19 13:09
Hi,
Please check if the problem is fixed with version 2.1.2.2.
Thanks, Stefan

**Comment by KITT3000** [comment] 2017-06-19 14:28
No error :P

**Closed** 2017-06-19 14:33 UTC
