### ISSUE TITLE
siloKing SelfLine Compact 1612

### ISSUE THREAD

**Issue by zed636** [Mogli12/GearboxAddon#66] opened 2016-11-21 00:07 UTC
Hi Mogli, I find this error using GearboxAddon v1.9.3.3 when I buy the siloKing SelfLine Compact 1612:
data/vehicles/steerable/siloking/siloKingSelfLineCompact1612.i3d (141.90) ms
FS17_GearboxAddon: looking for default configuration (defaultHydrostatic1)
gearboxMogli: Initialization of client...
FS17_GearboxAddon: defaultHydrostatic1 inserted into data/vehicles/steerable/siloking/siloKingSelfLineCompact1612.xml (i)
Error in updateVehiclePhysics :dataS/scripts/vehicles/specializations/Drivable.lua:0: attempt to perform arithmetic on a nil value
Error in updateVehiclePhysics :C:/Users/xxx/Documents/My Games/FarmingSimulator2017/mods/FS17_GearboxAddon/gearboxMogli.lua:6792: attempt to perform arithmetic on local 'dt' (a nil value)
I have FS17 version: 1.3.0.0 1.3RC4
Thank for your mods!
Zed636

**Comment by Mogli12** [comment] 2016-11-21 11:52
Hi,
I cannot reproduce it with 1.9.3.6.
Regards, Stefan

**Comment by Mogli12** [comment] 2016-11-22 07:48
Hi,
I was now able to reproduce it. I think you had cruise control on while leaving the vehicle. It is fixed with version 1.9.3.7.
Regards, Stefan

**Closed by Mogli12** 2016-11-22 07:48 UTC
