### ISSUE TITLE
tractor with cvt not accelerating

### ISSUE THREAD

**Issue by Quintto** [Mogli12/GearboxAddon#205] opened 2017-08-12 13:37 UTC
in my savegame i just bought a fendt 828, to run the big kuhn triples
however it seems to not want to start driving while mowing or when on a hill. (when it is driving it is fine until you encounter a hill, then it loses RPM and stops driving)
even empty it pulls off really slowly.
running gearboxmod version: 2.1.6.1

XML of the fendt:

[fendt800.txt](https://github.com/Mogli12/GearboxAddon/files/1219803/fendt800.txt)

update:
I added a proper gearbox config to the tractor (so the list with torque values instead of using the ingame power system) but that didn't fix the problem after that I tried it with an ingame 930 with the same mowers and it still doesn't want to start driving, so I'm thinking its something to do with this version of gearbox mod

**Comment by Mogli12** [comment] 2017-08-12 21:56
Hello,
The problem is that the traction is way too high in FS17. I found an article about the Fendt 300 Vario. It can only transfer a limited amount of torque but that is still enough to spin the wheels. But spinning the wheels does not really happen in FS17.
I hope the problem is fixed with version 2.1.6.7.
BR

**Comment by Anonymous-any** [comment] 2017-08-12 22:01
Hi not only cvt for me somtimes that happen randomly and vehicles I use joystick that can happen but sometimes too with keyboard key too the engine go RPM but vehicle spin (not for real of course) it look like a gear disengaged ...

**Comment by Quintto** [comment] 2017-08-13 18:39
that seems to be a lot better, thanks!

**Closed** 2017-08-13 19:44 UTC
